version: "3.1" # Версия docker-compose
networks: # наши связи для подключения бэк и фронт
  backend:
    driver: bridge # соединение побочной ветви скажем так
  frontend:
    driver: bridge # соединение побочной ветви скажем так

volumes: # хранилище скажем так для нашей бд
  postgres_data_volume:

services:
  db: # обозначаем сервис нашей базы данных
    image: postgres # имя образа нашей бд
    networks: # название связи
      - backend
    volumes:
      - postgres_data_volume:/var/lib/postgresql/data  # здесь мы указываем где будем хранить наши данные в образе бд
    environment: # переменные среды при создания базы данных
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=postgres
      - POSTGRES_DB=payment_module


  payment_module: # наш образ приложения
    image: kitamuro/attractor:latest  # название образа (здесь уже образ из DockerHub)
    networks: # связи так как приложение должно иметь возможность скажем так из бд - приложение - фронт
      - backend
      - frontend
    environment: # здесь мы указываем переменные среды для подключения к образу базы данных
      - DB_CONNECTION=jdbc:postgresql://db:5432/payment_module # здесь вместо localhost мы используем бд образа потому что мы не связаны теперь с локальной бд
      - DB_USERNAME=postgres
      - DB_PASSWORD=12345
    depends_on: # здесь указываем зависимость нашей образа бд
      - "db"

  front: # здесь устанавливаем настройки фронта
    image: nginx # имя образа
    networks:
      - frontend
    ports: # порт 8080 внутренний наш а 80 это на уровне образа nginx
      - 8040:80
    volumes: # здесь мы указываем надстройки конфигурации ( в корневой папке создаем папку configs и там nginx.conf )
      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on: # здесь указываем зависимость с приложением
      - "payment_module"

